Repository BOONG-O-BBANG/BOONG-O-BBANG_SERVER, pull requests merged in 2023-09, with the labels that each got.

#5 [Setting] build.gradle 설정
  build.gradle
Labels: ⚙ Setting

#9 [Refactor] UserController signUp 메서드 반환값 수정
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#11 [Feature] 유저 유효성 검사
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserValidateDto.java
  src/main/java/com/project/boongobbang/repository/UserRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#13 [Setting] build.gradle 설정
  build.gradle
Labels: ⚙ Setting

#15 [Feature] 로그인 기능
  src/main/java/com/project/boongobbang/config/SecurityConfig.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/token/TokenResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignInDto.java
  src/main/java/com/project/boongobbang/exception/ExceptionManager.java
  src/main/java/com/project/boongobbang/jwt/JwtAuthFilter.java
  src/main/java/com/project/boongobbang/jwt/JwtUtils.java
  src/main/java/com/project/boongobbang/repository/redis/RedisRefreshTokenRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserRepository.java
  src/main/java/com/project/boongobbang/service/CustomUserDetailsService.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#19 [Feature] 리포지토리 생성
  src/main/java/com/project/boongobbang/domain/entity/user/User.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserScore.java
  src/main/java/com/project/boongobbang/repository/Room/RoomRepository.java
  src/main/java/com/project/boongobbang/repository/Roommate/NotificationRepository.java
  src/main/java/com/project/boongobbang/repository/Roommate/RoommateRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserScoreRepository.java
Labels: ✨ Feature

#22 [Feature] DTO 추가
  src/main/java/com/project/boongobbang/domain/dto/notification/NotificationResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/room/RoomResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/room/RoomSearchDto.java
  src/main/java/com/project/boongobbang/domain/dto/roommate/HistoryResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/roommate/RoommateResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserProfileDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignInDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignUpDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSimpleDto.java
  src/main/java/com/project/boongobbang/domain/entity/user/User.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserAverageScore.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserScore.java
Labels: ✨ Feature

#23 [Feature] 리포지토리 생성
  src/main/java/com/project/boongobbang/domain/dto/roommate/NotificationResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserResponseDto.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserAverageScore.java
  src/main/java/com/project/boongobbang/repository/room/RoomRepository.java
  src/main/java/com/project/boongobbang/repository/roommate/NotificationRepository.java
  src/main/java/com/project/boongobbang/repository/roommate/RoommateRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserScoreRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature, 🔨 Refactor

#26 [Feature] User CRUD 기능 구현
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserUpdateRequestDto.java
  src/main/java/com/project/boongobbang/domain/entity/user/User.java
  src/main/java/com/project/boongobbang/repository/user/UserRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#27 [Feature] Swagger 추가
  src/main/java/com/project/boongobbang/config/SecurityConfiguration.java
  src/main/java/com/project/boongobbang/config/SwaggerConfiguration.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignUpDto.java
Labels: ✨ Feature

#30 [BUG] access token이 만료될 시, 갱신 안되는 문제 해결
  src/main/java/com/project/boongobbang/jwt/JwtAuthFilter.java
  src/main/java/com/project/boongobbang/jwt/JwtUtils.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: 🐞 BugFix

#32 [Feature] 로그인 기능 수정
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/token/TokenResponseDto.java
  src/main/java/com/project/boongobbang/exception/ErrorCode.java
  src/main/java/com/project/boongobbang/exception/ExceptionManager.java
  src/main/java/com/project/boongobbang/jwt/JwtAuthFilter.java
  src/main/java/com/project/boongobbang/jwt/JwtUtils.java
  src/main/java/com/project/boongobbang/service/CustomUserDetailsService.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#34 [Feature] 토큰 재발행 기능
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/ReIssueDto.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#38 [Feature] 유저 프로필 이미지 기능 추가
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignUpDto.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserPhoto.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#40 [Feature] 신청 관련 API 구현
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/RoommateController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#43 [Feature] 룸메이트 관련 기능 추가
  src/main/java/com/project/boongobbang/controller/RoommateController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserResponseDto.java
  src/main/java/com/project/boongobbang/domain/entity/user/UserScore.java
  src/main/java/com/project/boongobbang/repository/roommate/RoommateRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#44 [Feature] 알림 관련 기능 추가
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#46 [Feature] 유저 평가 기능 추가
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/repository/user/UserScoreRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#48 [Feature] 룸메이트 추천기능 추가
  src/main/java/com/project/boongobbang/BoongobbangApplication.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/entity/user/User.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: ✨ Feature

#50 [Feature] 유저 룸메이트 해제 기능 수정
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/RoommateController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/repository/roommate/RoommateRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: 🔨 Refactor

#52 [BUG] validate api 작동 해결
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserValidateDto.java
Labels: 🐞 BugFix

#54 [Refactor] User responseDto 생년월일 표시 변경
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserProfileDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserResponseDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserSimpleDto.java
Labels: 🔨 Refactor

#59 [Refactor] Jwt Exception handling 수정
  src/main/java/com/project/boongobbang/jwt/JwtAuthFilter.java
  src/main/java/com/project/boongobbang/jwt/JwtUtils.java
Labels: 🔨 Refactor

#60 [Refactor] 관리자 전용 API 설정
  src/main/java/com/project/boongobbang/config/SecurityConfiguration.java
  src/main/java/com/project/boongobbang/controller/AdminController.java
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/RoommateController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: 🔨 Refactor

#62 [Refactor] SeoulGu Enum수정 (#61)
  src/main/java/com/project/boongobbang/enums/SeoulGu.java
Labels: 🔨 Refactor

#64 [Refactor] build.gradle 수정
  build.gradle
Labels: 🔨 Refactor

#73 [BUG] 테스트 코드 빌드 에러 해결
  src/test/java/com/project/boongobbang/BoongobbangApplicationTests.java
Labels: 🐞 BugFix

#83 [Feature] Dockerfile 생성
  Dockerfile
Labels: ✨ Feature

#85 [Feature] deploy.sh 작성
  scripts/deploy.sh
Labels: ✨ Feature

#87 [Deploy] appspec.yml 작성
  .gitignore
  appspec.yml
Labels: 🌏 Deploy

#89 [BUG] AWS CodeDeploy AllowTraffic 이벤트에서 무한 로딩 문제 해결
  src/main/java/com/project/boongobbang/config/SecurityConfiguration.java
Labels: 🐞 BugFix

#91 [BUG] AWS CodeDeploy AllowTraffic 이벤트에서 무한 로딩 문제
  src/main/java/com/project/boongobbang/config/SecurityConfiguration.java
  src/main/java/com/project/boongobbang/controller/HealthController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
Labels: 🐞 BugFix

#95 [Feat] Redis DB 설치 자동화
  scripts/deploy.sh
Labels: ✨ Feature

#101 [BUG] CORS 405 에러
  src/main/java/com/project/boongobbang/config/SecurityConfiguration.java
Labels: 🐞 BugFix

#103 [Feat] 입력 유효성 검사
  build.gradle
  src/main/java/com/project/boongobbang/domain/dto/user/UserSignUpDto.java
  src/main/java/com/project/boongobbang/domain/dto/user/UserUpdateRequestDto.java
Labels: ✨ Feature

#105 [Feat] 더미데이터 실제 이름처럼 수정
  src/main/java/com/project/boongobbang/BoongobbangApplication.java
Labels: ✨ Feature

#106 [BUG] CORS 405 에러
  src/main/java/com/project/boongobbang/controller/AdminController.java
  src/main/java/com/project/boongobbang/controller/HealthController.java
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/RoommateController.java
  src/main/java/com/project/boongobbang/controller/UserController.java
Labels: 🐞 BugFix

#107 Hotfix/#100
  src/main/java/com/project/boongobbang/config/WebConfiguration.java
  src/main/java/com/project/boongobbang/controller/NotificationController.java
  src/main/java/com/project/boongobbang/controller/RoommateController.java
Labels: 🐞 BugFix

#109 [BUG] Docker 미사용 이미지 있는 경우 삭제
  scripts/deploy.sh
Labels: 🐞 BugFix

#112 [BUG] deploy.sh timeout
  appspec.yml
Labels: 🐞 BugFix

#114 [BUG] CORS 설정에서 발생하는 문제
  src/main/java/com/project/boongobbang/config/WebConfiguration.java
Labels: 🐞 BugFix

#115 [Feature] 룸메이트 추천 알고리즘 적용
  src/main/java/com/project/boongobbang/controller/UserController.java
  src/main/java/com/project/boongobbang/repository/user/UserRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserTypeFavorRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
  src/main/java/com/project/boongobbang/util/UserTypeFavor.java
Labels: ✨ Feature

#117 [BUG] CORS 설정에서 발생하는 문제
  src/main/java/com/project/boongobbang/config/WebConfiguration.java
Labels: 🐞 BugFix

#119 [BUG] 유저 삭제 시 SQL 에러 발생
  src/main/java/com/project/boongobbang/BoongobbangApplication.java
  src/main/java/com/project/boongobbang/domain/entity/user/User.java
  src/main/java/com/project/boongobbang/repository/roommate/NotificationRepository.java
  src/main/java/com/project/boongobbang/repository/roommate/RoommateRepository.java
  src/main/java/com/project/boongobbang/repository/user/UserScoreRepository.java
  src/main/java/com/project/boongobbang/service/UserService.java
Labels: 🐞 BugFix
